/**
 * MASTER PLUGIN REGISTRY (A to Z)
 * Auto-generated by build-plugins.js
 */
import * as utils from './utils.js';

import * as pluginA from './A/index.js';
import * as pluginB from './B/index.js';
import * as pluginC from './C/index.js';
import * as pluginD from './D/index.js';
import * as pluginE from './E/index.js';
import * as pluginF from './F/index.js';
import * as pluginG from './G/index.js';
import * as pluginH from './H/index.js';
import * as pluginI from './I/index.js';
import * as pluginJ from './J/index.js';
import * as pluginK from './K/index.js';
import * as pluginL from './L/index.js';
import * as pluginM from './M/index.js';
import * as pluginN from './N/index.js';
import * as pluginO from './O/index.js';
import * as pluginP from './P/index.js';
import * as pluginQ from './Q/index.js';
import * as pluginR from './R/index.js';
import * as pluginS from './S/index.js';
import * as pluginT from './T/index.js';
import * as pluginU from './U/index.js';
import * as pluginV from './V/index.js';
import * as pluginW from './W/index.js';
import * as pluginX from './X/index.js';
import * as pluginY from './Y/index.js';
import * as pluginZ from './Z/index.js';

export const plugins = {
  'A': pluginA,
  'B': pluginB,
  'C': pluginC,
  'D': pluginD,
  'E': pluginE,
  'F': pluginF,
  'G': pluginG,
  'H': pluginH,
  'I': pluginI,
  'J': pluginJ,
  'K': pluginK,
  'L': pluginL,
  'M': pluginM,
  'N': pluginN,
  'O': pluginO,
  'P': pluginP,
  'Q': pluginQ,
  'R': pluginR,
  'S': pluginS,
  'T': pluginT,
  'U': pluginU,
  'V': pluginV,
  'W': pluginW,
  'X': pluginX,
  'Y': pluginY,
  'Z': pluginZ,
};

export const pluginList = [
  pluginA,
  pluginB,
  pluginC,
  pluginD,
  pluginE,
  pluginF,
  pluginG,
  pluginH,
  pluginI,
  pluginJ,
  pluginK,
  pluginL,
  pluginM,
  pluginN,
  pluginO,
  pluginP,
  pluginQ,
  pluginR,
  pluginS,
  pluginT,
  pluginU,
  pluginV,
  pluginW,
  pluginX,
  pluginY,
  pluginZ,
];

export { utils };

// Group by Banks for VJ Console UI
export const bankGroups = [
  {
    id: 'flash',
    title: '⚡ BANK 1: FLASH & STROBE 爆闪与快门',
    plugins: ['A', 'S', 'J', 'G'].map(k => plugins[k])
  },
  {
    id: 'lasers',
    title: '💥 BANK 2: LASERS & CROSSHAIRS 激光与光刃',
    plugins: ['B', 'C', 'F', 'L', 'Q', 'X'].map(k => plugins[k])
  },
  {
    id: 'geometry',
    title: '🌀 BANK 3: GEOMETRY & PORTALS 几何与时空隧道',
    plugins: ['D', 'H', 'I', 'K', 'V', 'Z'].map(k => plugins[k])
  },
  {
    id: 'synthwave',
    title: '🌐 BANK 4: SYNTHWAVE & STAGE 赛博舞池与地平线',
    plugins: ['M', 'U', 'Y', 'P'].map(k => plugins[k])
  },
  {
    id: 'chaos',
    title: '✨ BANK 5: CELESTIAL & CHAOS 闪电星系与力场',
    plugins: ['E', 'N', 'O', 'R', 'T', 'W'].map(k => plugins[k])
  }
];
